// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgHxH-x8oJxBBWTeab1RxwOcSID3HgIFU',
    appId: '1:73683885617:web:b6e498c1f519eb480abf10',
    messagingSenderId: '73683885617',
    projectId: 'flutter-chat-app-8f4c2',
    authDomain: 'flutter-chat-app-8f4c2.firebaseapp.com',
    storageBucket: 'flutter-chat-app-8f4c2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC82WxXGnxagzblp9G3fEPgxlQi8iok1Ug',
    appId: '1:73683885617:android:0e33ea14e1a04e260abf10',
    messagingSenderId: '73683885617',
    projectId: 'flutter-chat-app-8f4c2',
    storageBucket: 'flutter-chat-app-8f4c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4w32JI_6MyAK0HBUzG0lRjCw3-c7fSZY',
    appId: '1:73683885617:ios:92b0a9de479717ea0abf10',
    messagingSenderId: '73683885617',
    projectId: 'flutter-chat-app-8f4c2',
    storageBucket: 'flutter-chat-app-8f4c2.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4w32JI_6MyAK0HBUzG0lRjCw3-c7fSZY',
    appId: '1:73683885617:ios:dcdb609aa730399d0abf10',
    messagingSenderId: '73683885617',
    projectId: 'flutter-chat-app-8f4c2',
    storageBucket: 'flutter-chat-app-8f4c2.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
